'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

limit = 4000000

fiblist = [0, 1]

evenfib = []

x,y = 0, 1
z = 0

while z < limit:
	z = x + y
	x = y
	y = z
	fiblist.append(z)

for f in fiblist:
	if f % 2 == 0:
		evenfib.append(f)

print(sum(evenfib))